#include <SDL2/SDL.h>
#include <SDL2/SDL_ttf.h>
#include <stdio.h>
#include <math.h>

// Screen Constants
#define MAX_X 1024
#define MAX_Y 768
#define SIDE_BAR_WIDTH 192
#define BORDER_SIZE 10

// Size of Rocket
#define ROCKET_WIDTH 32
#define ROCKET_HEIGHT 80

// Size of Spaceship
#define SPACE_SHIP_WIDTH 80
#define SPACE_SHIP_HEIGHT 64

//Bullet Constants
#define BULLET_SPEED 8
#define MAX_BULLETS 30
#define ROCKET_MOVE_DELAY 20

//Rocket Constants
#define ROCKET_SPEED 8
#define MAX_ROCKETS 6
#define BULLET_MOVE_DELAY 2

//Max Value Generated by randRocketAxis()
#define RAND_MAX 112

typedef struct
{
    int x;
    int y;
    int active;  // Flag to bullet is active or not
    int avaible; // Flag to bullet is avaible to shot
} Bullet;

typedef struct
{
    int x;
    int y;
    int active; // Flag to rocket is active or not
} Rocket;

Bullet bullets[MAX_BULLETS];
Rocket rockets[MAX_ROCKETS];

//Delay Counters
int rocketMoveCounter = 0; // Counter to control rocket movement speed
int bulletMoveCounter = 0; // Counter to control bullet movement speed

//Flags for status of pause and quit
int quit_flag = 0;
int pause_flag = 0;

//hold current key
char current_key = '1';

int bullet_count = MAX_BULLETS;

//coordinates of spaceship
int ship_x;
int ship_y;

int score = 0;

//string arrays for printing score and bullets count on screen
char score_str[3];   // maximum number of digits is 3
char bullets_str[2]; // maximum number of digits is 2

TTF_Font *font = NULL;

//Clears all screen
void clearScreen(SDL_Renderer *renderer)
{
    SDL_SetRenderDrawColor(renderer, 0, 0, 0, 255); // black
    SDL_RenderClear(renderer);
}

//Clears specific rectangle from screen
void SDLClearRect(SDL_Renderer *renderer, int x, int y, int x1, int x2)
{
    SDL_SetRenderDrawColor(renderer, 0, 0, 0, 255); // Black color
    SDL_Rect clearRect = {x, y, x1, x2};
    SDL_RenderFillRect(renderer, &clearRect);
}

//Draw Boundaries
void drawBoundaries(SDL_Renderer *renderer)
{
    SDL_Color textColor = {255, 255, 255, 255}; // White color
    // Draw top border
    SDL_Rect topBorder = {0, 0, MAX_X, BORDER_SIZE};
    SDL_RenderFillRect(renderer, &topBorder);

    // Draw bottom border
    SDL_Rect bottomBorder = {0, MAX_Y - BORDER_SIZE, MAX_X, BORDER_SIZE};
    SDL_RenderFillRect(renderer, &bottomBorder);

    // Draw left border
    SDL_Rect leftBorder = {0, BORDER_SIZE, BORDER_SIZE, MAX_Y - 2 * BORDER_SIZE};
    SDL_RenderFillRect(renderer, &leftBorder);

    // Draw SideBar
    SDL_Rect SideBar = {SIDE_BAR_WIDTH, BORDER_SIZE, BORDER_SIZE, MAX_Y - 2 * BORDER_SIZE};
    SDL_RenderFillRect(renderer, &SideBar);

    // Draw right border
    SDL_Rect rightBorder = {MAX_X - BORDER_SIZE, BORDER_SIZE, BORDER_SIZE, MAX_Y - 2 * BORDER_SIZE};
    SDL_RenderFillRect(renderer, &rightBorder);
}

// Convert an integer to its string representation
int intToString(int num, char *buffer)
{
    int i = 0;
    int digits = 0; // Variable to store the number of digits

    if (num == 0)
    {
        buffer[i++] = '0';
        digits = 1; // If the number is zero, it has one digit
    }
    else
    {
        // Calculate the number of digits
        int temp = num;
        while (temp != 0)
        {
            digits++;
            temp /= 10;
        }

        // Convert each digit to character and store in the buffer
        while (num != 0)
        {
            int digit = num % 10;
            buffer[i++] = '0' + digit;
            num /= 10;
        }
    }
    buffer[i] = '\0';

    // Reverse the string
    int start = 0;
    int end = i - 1;
    while (start < end)
    {
        char temp = buffer[start];
        buffer[start] = buffer[end];
        buffer[end] = temp;
        start++;
        end--;
    }

    return digits; // Return the number of digits
}

//Write string on Screen
void graphicsWriteString(SDL_Renderer *renderer, int x, int y, const char *text, TTF_Font *font)
{
    SDL_Color textColor = {255, 255, 255}; // White color
    SDL_Surface *surface = TTF_RenderText_Solid(font, text, textColor);
    if (surface == NULL)
    {
        printf("Failed to render text! SDL_ttf Error: %s\n", TTF_GetError());
        return;
    }

    SDL_Texture *texture = SDL_CreateTextureFromSurface(renderer, surface);
    if (texture == NULL)
    {
        printf("Failed to create texture! SDL_Error: %s\n", SDL_GetError());
        SDL_FreeSurface(surface);
        return;
    }

    SDL_Rect dstRect = {x, y, surface->w, surface->h}; // Position and size
    SDL_RenderCopy(renderer, texture, NULL, &dstRect);

    SDL_DestroyTexture(texture);
    SDL_FreeSurface(surface);
}

//Print Score on Screen
void printScore(SDL_Renderer *renderer, int x, int y)
{
    SDLClearRect(renderer, x, y, 18, 16);
    SDL_SetRenderDrawColor(renderer, 255, 255, 255, 255); // White color
    int num_digits = intToString(score, score_str);
    graphicsWriteString(renderer, x, y, score_str, font);
}

//Count how many bullet left
void bulletCounter()
{
    bullet_count = 0;
    for (int i = 0; i < MAX_BULLETS; i++)
    {
        if (bullets[i].avaible)
        {
            bullet_count += 1;
        }
    }
}

//Print how many bullets left
void printBulletCount(SDL_Renderer *renderer, int x, int y)
{

    SDLClearRect(renderer, x, y, 18, 16);
    SDL_SetRenderDrawColor(renderer, 255, 255, 255, 255); // White color
    int num_digits = intToString(bullet_count, bullets_str);
    graphicsWriteString(renderer, x, y, bullets_str, font);
    if (bullet_count < 10)
        graphicsWriteString(renderer, x + 8, y, " ", font);
}

//Write Game Info
void info(SDL_Renderer *renderer, TTF_Font *font)
{
    SDL_SetRenderDrawColor(renderer, 255, 255, 255, 255); // Set color to draw (white)
    graphicsWriteString(renderer, 16, 15, "Welcome!", font);
    graphicsWriteString(renderer, 16, 30, "Save the World!", font);
    graphicsWriteString(renderer, 16, 45, "by Eren Karadeniz", font);
    graphicsWriteString(renderer, 16, 60, "200101070", font);

    graphicsWriteString(renderer, 16, 85, "Keys", font);
    graphicsWriteString(renderer, 16, 100, "A to move left", font);
    graphicsWriteString(renderer, 16, 115, "D to move right", font);
    graphicsWriteString(renderer, 16, 130, "Space to Shot", font);
    graphicsWriteString(renderer, 16, 145, "Q to quit game", font);
    graphicsWriteString(renderer, 16, 160, "R to restart game", font);
    graphicsWriteString(renderer, 16, 175, "P to pause game", font);
    graphicsWriteString(renderer, 16, 190, "Win after reach", font);
    graphicsWriteString(renderer, 16, 205, "25 Score", font);
}

// Initialize game screen
void intro(SDL_Renderer *renderer)
{

    drawBoundaries(renderer);

    info(renderer, font);

    graphicsWriteString(renderer, 16, 250, "Bullets:", font);
    printBulletCount(renderer, 88, 250);

    graphicsWriteString(renderer, 16, 265, "Score:", font);
    printScore(renderer, 80, 265);
}

// Draw A shape for spaceship Draw
void drawA(SDL_Renderer *renderer, int x, int y, int w, int h)
{
    SDL_RenderDrawLine(renderer, x, y, x + w + 3, y + h + 3);
    SDL_RenderDrawLine(renderer, x, y, x - w - 3, y + h + 3);

    SDL_RenderDrawLine(renderer, x - 10, y + 10, x - 10, y + 10 + h + 5);
    SDL_RenderDrawLine(renderer, x + 10, y + 10, x + 10, y + 10 + h + 5);
    SDL_RenderDrawLine(renderer, x - 10, y + 15, x + 10, y + 15);
}

//Draw Circle
void drawCircle(SDL_Renderer *renderer, int centerX, int centerY, int radius)
{
    SDL_SetRenderDrawColor(renderer, 255, 255, 255, 255); // Set color to white
    for (int x = -radius; x <= radius; x++)
    {
        int y = (int)sqrt(radius * radius - x * x);              // Calculate y-coordinate based on the equation of a circle
        SDL_RenderDrawPoint(renderer, centerX + x, centerY + y); // Draw top half of circle
        SDL_RenderDrawPoint(renderer, centerX + x, centerY - y); // Draw bottom half of circle
    }
}

//Draws Spaceship
void drawSpaceship(SDL_Renderer *renderer, int x, int y, int w, int h)
{
    SDL_SetRenderDrawColor(renderer, 255, 255, 255, 255); // White color
    // Draw A
    drawA(renderer, x, y, w, h);
    drawA(renderer, x + 70, y, w, h);
    drawA(renderer, x, y + 20, w, h);
    drawA(renderer, x + 70, y + 20, w, h);

    // Draw I
    SDL_RenderDrawLine(renderer, x + 35, y, x + 35, y + h + 6);
    // Draw -
    SDL_RenderDrawLine(renderer, x + 35 - w + 1, y, x + 35 + w - 1, y);
    SDL_RenderDrawLine(renderer, x + 35 - w + 1, y + h + 6, x + 35 + w - 1, y + h + 6);

    // Draw /
    SDL_RenderDrawLine(renderer, x + 30, y + 20, x + 30 - w - 3, y + 20 + h + 3);
    // Draw '\'
    SDL_RenderDrawLine(renderer, x + 40, y + 20, x + 40 + w + 3, y + 20 + h + 3);
    // Draw -
    SDL_RenderDrawLine(renderer, x + 30, y + 22, x + 30 + w + 6, y + 22);

    // Draw /
    SDL_RenderDrawLine(renderer, x + 10, y + 45, x + 10 - w, y + 45 + h);
    // Draw o

    drawCircle(renderer, x + 20, y + 45 - w - 2, 5);
    drawCircle(renderer, x + 35, y + 45 - w - 2, 5);
    drawCircle(renderer, x + 50, y + 45 - w - 2, 5);

    // Draw '\'
    SDL_RenderDrawLine(renderer, x + 60, y + 45, x + 60 + w, y + 45 + h);
}

// Clears the old position of the spaceship
void clearSpaceship(SDL_Renderer *renderer, int x, int y, int w, int h)
{
    // Calculate bottom-right corner coordinates
    int x2 = x + 92;
    int y2 = y + 54; // Maximum y-coordinate for the spaceship

    // Set the color to clear (usually you would set this to your background color)
    SDL_SetRenderDrawColor(renderer, 0, 0, 0, 255); // Black color

    // Define the rectangle to clear
    SDL_Rect clearRect = {x - 10, y, x2 - x, y2 - y};

    // Clear the rectangle covering the spaceship
    SDL_RenderFillRect(renderer, &clearRect);
}

void drawBullet(SDL_Renderer *renderer, int x, int y)
{
    // Draw the '^' character
    SDL_SetRenderDrawColor(renderer, 255, 255, 255, 255); // Set color to draw (white)

    // Draw the points to form the '^' character
    SDL_RenderDrawPoint(renderer, x, y);         // Top center point
    SDL_RenderDrawPoint(renderer, x - 1, y + 1); // Upper left point
    SDL_RenderDrawPoint(renderer, x - 2, y + 2); // Upper left point
    SDL_RenderDrawPoint(renderer, x - 3, y + 3); // Upper left point
    SDL_RenderDrawPoint(renderer, x + 1, y + 1); // Upper right point
    SDL_RenderDrawPoint(renderer, x + 2, y + 2); // Upper right point
    SDL_RenderDrawPoint(renderer, x + 3, y + 3); // Upper right point
}

//Move bullet
void moveBullet(SDL_Renderer *renderer, int index)
{
    if (bulletMoveCounter % BULLET_MOVE_DELAY == 0)
    {

        // Clear previous bullet position
        SDLClearRect(renderer, bullets[index].x - 3, bullets[index].y, 7, 4);
        if (bullets[index].y > 20)
        {

            bullets[index].y -= BULLET_SPEED; // Move the bullet upwards
            // Draw '^' character at the new position
            SDL_SetRenderDrawColor(renderer, 255, 255, 255, 255);        // Set color to draw (white)
            drawBullet(renderer, bullets[index].x, bullets[index].y); // Draw the bullet
        }
        else
            bullets[index].active = 0;
    }
}

//Control movement of all bullets
void moveBullets(SDL_Renderer *renderer)
{
    // Move all active bullets
    for (int index = 0; index < MAX_BULLETS; index++)
    {
        if (!pause_flag)
        {
            if (bullets[index].active && !bullets[index].avaible)
            {
                drawBullet(renderer, bullets[index].x, bullets[index].y); // Draw the bullet
                moveBullet(renderer, index);
            }
        }
    }

    // Increment the bullet move counter
    bulletMoveCounter++;

    // Reset the counter to prevent overflow
    if (bulletMoveCounter >= BULLET_MOVE_DELAY)
        bulletMoveCounter = 0;
}

void shotBullet(Bullet *bullet)
{
    bullet->active = 1;
    bullet->avaible = 0;
    bullet->x = ship_x + 32; // Adjust bullet position to appear from spaceship's center
    bullet->y = ship_y - 16;
}

//Draw Rocket
void drawRocket(SDL_Renderer *renderer, int x, int y)
{
    // Draw \||/
    SDL_RenderDrawLine(renderer, x, y - 10 - 8, x + 10, y - 10);
    SDL_RenderDrawLine(renderer, x + 10, y - 8, x + 10, y - 28);
    SDL_RenderDrawLine(renderer, x + 20, y - 8, x + 20, y - 28);
    SDL_RenderDrawLine(renderer, x + 20, y - 8, x + 30, y - 18);

    // Draw ___
    SDL_RenderDrawLine(renderer, x, y, x + 30, y);

    // Draw |o|
    SDL_RenderDrawLine(renderer, x, y + 25, x, y - 20);
    SDL_Rect circle = {x + 15 - 4, y + 10 - 4, 8, 8}; // Rectangle for circle
    SDL_RenderDrawRect(renderer, &circle);
    SDL_RenderDrawLine(renderer, x + 30, y + 25, x + 30, y - 20);

    // Draw '\'
    SDL_RenderDrawLine(renderer, x, y + 15, x + 15, y + 30);
    // Draw /
    SDL_RenderDrawLine(renderer, x + 30, y + 15, x + 15, y + 30);
}

//ClearRocket
void clearRocket(SDL_Renderer *renderer, int x, int y)
{
    // Calculate bottom-right corner coordinates
    int x2 = x + ROCKET_WIDTH;
    int y2 = y + ROCKET_HEIGHT; // Maximum y-coordinate for the spaceship

    // Set the color to clear (usually you would set this to your background color)
    SDL_SetRenderDrawColor(renderer, 0, 0, 0, 255); // Black color

    // Define the rectangle to clear
    SDL_Rect clearRect = {x, y - 40, x2 - x, y2 - y};

    // Clear the rectangle covering the spaceship
    SDL_RenderFillRect(renderer, &clearRect);
}

//Get System Timer for random
unsigned int getSystemTimerValue()
{
    unsigned int val;
    // Read the value of the system timer (assuming x86 architecture)
    asm volatile("rdtsc" : "=a"(val));
    return val;
}

// Define some global variables for the random number generator
static unsigned long next;

//Generate a pseudo-random integer
int rand(void)
{
    next = getSystemTimerValue();
    next = next * 1103515245 + 12345;
    return (unsigned int)(next / 65536) % RAND_MAX;
}

//Randomize X axis of Rockets due to block collision of rockets
int randRocketAxis()
{
    int min_x = SIDE_BAR_WIDTH / 8 + 1;
    int max_x = MAX_X / 8 - ROCKET_WIDTH / 8;
    int x = rand(); // 1 - 88
    while (min_x > x || x > max_x)
    {
        x = rand();
    }
    return x + 8;
}

//Generate a single rocket from passive rocket
void generateRocket(Rocket *rocket)
{
    int newRocketX, newRocketY;
    int collisionDetected;

    do
    {
        // Generate random position for the new rocket
        newRocketX = 8 * randRocketAxis(); // Adjust range to prevent overflow
        newRocketY = 52;                   // Adjust range as needed

        // Check for collision with existing rockets based on X position only
        collisionDetected = 0;
        for (int j = 0; j < MAX_ROCKETS; j++)
        {
            if (rockets[j].active &&
                (newRocketX >= rockets[j].x - 20 - ROCKET_WIDTH && newRocketX <= rockets[j].x + ROCKET_WIDTH)) // Check only X position
            {
                collisionDetected = 1;
                break;
            }
        }
    } while (collisionDetected);

    // Set the position of the new rocket
    rocket->x = newRocketX;
    rocket->y = newRocketY;
    rocket->active = 1;
}

//Generate Rockets
void generateRockets()
{
    // Generate new rockets if there are inactive rockets
    for (int i = 0; i < MAX_ROCKETS; i++)
    {
        if (!rockets[i].active)
        {
            generateRocket(&rockets[i]);
        }
    }
}

//Move single rocket
void moveRocket(SDL_Renderer *renderer, int index)
{
    if (rocketMoveCounter % ROCKET_MOVE_DELAY == 0)
    {                                                              // Move the rocket every ROCKET_MOVE_DELAY frames
        clearRocket(renderer, rockets[index].x, rockets[index].y); // Clear previous rocket position
        rockets[index].y += ROCKET_SPEED;                          // Move the rocket downwards
        drawRocket(renderer, rockets[index].x, rockets[index].y);
    }
}

//Control movement of single rocket
void moveRockets(SDL_Renderer *renderer)
{
    // Draw and move the rocket
    for (int i = 0; i < MAX_ROCKETS; i++)
    {
        if (!pause_flag)
        {
            if (rockets[i].active)
            {
                drawRocket(renderer, rockets[i].x, rockets[i].y);
                moveRocket(renderer, i);
            }
        }
    }

    // Increment the rocket move counter
    rocketMoveCounter++;
    // Reset the counter to prevent overflow
    if (rocketMoveCounter >= ROCKET_MOVE_DELAY)
        rocketMoveCounter = 0;
    if (current_key != 'p')
    {
        generateRockets();
    }
}

//Init all bullets
void initBullets()
{
    for (int i = 0; i < MAX_BULLETS; i++)
    {
        bullets[i].x = 1;
        bullets[i].y = 1;
        bullets[i].active = 0;
        bullets[i].avaible = 1;
    }
}

//Init all rockets
void initRockets()
{
    for (int i = 0; i < MAX_ROCKETS; i++)
    {
        int newRocketX, newRocketY;
        int collisionDetected;

        do
        {
            // Generate random position for the new rocket
            newRocketX = 8 * randRocketAxis();
            newRocketY = 52;

            // Check for collision with existing rockets based on X position only
            collisionDetected = 0;
            for (int j = 0; j < i; j++)
            {
                if (rockets[j].active &&
                    (newRocketX >= rockets[j].x - ROCKET_WIDTH && newRocketX <= rockets[j].x + ROCKET_WIDTH)) // Check only X position
                {
                    collisionDetected = 1;
                    i = 0;
                    break;
                }
            }
        } while (collisionDetected);

        // Set the position of the new rocket
        rockets[i].x = newRocketX;
        rockets[i].y = newRocketY;
        rockets[i].active = 1;
    }
}

//Check for collision between bullet and rocket
int collisionBullet(SDL_Renderer *renderer)
{
    for (int i = 0; i < MAX_BULLETS; i++)
    {
        if (bullets[i].active)
        {
            for (int j = 0; j < MAX_ROCKETS; j++)
            {
                if (rockets[j].active &&
                    bullets[i].x >= rockets[j].x - 8 && bullets[i].x < rockets[j].x + ROCKET_WIDTH &&
                    bullets[i].y >= rockets[j].y && bullets[i].y < rockets[j].y + ROCKET_HEIGHT)
                {
                    score += 1;

                    printScore(renderer, 80, 265);
                    bullets[i].active = 0; // Deactivate bullet
                    rockets[j].active = 0; // Deactivate rocket
                    SDLClearRect(renderer, bullets[i].x - 3, bullets[i].y, 7, 4);
                    clearRocket(renderer, rockets[j].x, rockets[j].y);
                    break;
                }
            }
        }
    }
}

//Game Over when player loses
void gameOver(SDL_Renderer *renderer)
{
    clearScreen(renderer);
    info(renderer, font);
    drawBoundaries(renderer);
    graphicsWriteString(renderer, (MAX_X - SIDE_BAR_WIDTH) / 2 + 30, MAX_Y / 2 + 15, "You lost, Press R for Play Again", font);
    graphicsWriteString(renderer, (MAX_X - SIDE_BAR_WIDTH) / 2 + 140, MAX_Y / 2 + 30, "Score: ", font);
    graphicsWriteString(renderer, (MAX_X - SIDE_BAR_WIDTH) / 2 + 200, MAX_Y / 2 + 30, score_str, font);
    SDL_RenderPresent(renderer);
}

//Check for collision between rocket and spaceship
void collisionSpaceShip(SDL_Renderer *renderer)
{
    for (int i = 0; i < MAX_ROCKETS; i++)
    {
        // Check if any of the edges of the rocket box lie outside the spaceship box

        if (ship_x <= rockets[i].x + ROCKET_WIDTH - 1 && ship_x + SPACE_SHIP_WIDTH - 1 >= rockets[i].x && rockets[i].y + ROCKET_HEIGHT - 40 >= ship_y)
        {
            quit_flag = 1;
            gameOver(renderer);
            graphicsWriteString(renderer, (MAX_X - SIDE_BAR_WIDTH) / 2 + 30, MAX_Y / 2, "Spaceship destroyed by rocket", font);
        }
    }
}

//Init Game
void init(SDL_Renderer *renderer)
{
    // Set background color

    clearScreen(renderer);
    initBullets();
    initRockets();
    intro(renderer);
    drawBoundaries(renderer);

    ship_x = (MAX_X + SIDE_BAR_WIDTH) / 2 - SPACE_SHIP_WIDTH / 4; // base x of spaceship 49th pixel
    ship_y = MAX_Y - SPACE_SHIP_HEIGHT;                           // base y of spaceship 87th pixel
    SDL_RenderPresent(renderer);
}

//Quit game when pressed quit
void quitGame(SDL_Renderer *renderer)
{
    clearScreen(renderer);
    drawBoundaries(renderer);
    info(renderer, font);
    graphicsWriteString(renderer, MAX_X / 2, MAX_Y / 2, "Press R for Play Again", font);
}

//Restart game when pressed restart
void restartGame(SDL_Renderer *renderer)
{
    init(renderer); // Initialize the game
}

//Handle how the program runs based on which key is pressed
void handleUserInput(SDL_Renderer *renderer, char current_key, Bullet bullets[MAX_BULLETS])
{
    if (!pause_flag)
    {
        switch (current_key)
        {
        case 'a':
            if (ship_x - 1 > SIDE_BAR_WIDTH + 20)
            {
                clearSpaceship(renderer, ship_x, ship_y, 4, 4);
                ship_x -= 8;
            }
            break;
        case 'd':
            if (ship_x + SPACE_SHIP_WIDTH < MAX_X - 16)
            {
                clearSpaceship(renderer, ship_x, ship_y, 4, 4);
                ship_x += 8;
            }
            break;
        case ' ':
            for (int i = 0; i < MAX_BULLETS; i++)
            {
                if (!bullets[i].active && bullets[i].avaible)
                {
                    shotBullet(&bullets[i]);
                    bulletCounter();
                    printBulletCount(renderer, 88, 250);
                    break;
                }
            }
            break;
        case 'q':
            SDL_Quit();
            break;
        case 'r':
            score = 0;
            quit_flag = 0;
            bullet_count = MAX_BULLETS;
            restartGame(renderer); // Restart the game
            break;
        case 'p':
            pause_flag = !pause_flag; // Toggle pause_flag
            if (pause_flag)
            {
                graphicsWriteString(renderer, MAX_X / 2, MAX_Y / 2, "Paused, Press p to continue", font);
            }
            break;
        }
    }
    else
    {
        if (current_key == 'p')
        {
            pause_flag = 0;
            SDLClearRect(renderer, MAX_X / 2, MAX_Y / 2, 245, 20);
        }
    }
}

//Win condition
void winGame(SDL_Renderer *renderer)
{
    clearScreen(renderer);
    info(renderer, font);
    drawBoundaries(renderer);
    graphicsWriteString(renderer, MAX_X / 2, MAX_Y / 2, "You Win!", font);
    graphicsWriteString(renderer, MAX_X / 2, MAX_Y / 2 + 15, "Press R for Play Again", font);
    // Update screen
    SDL_RenderPresent(renderer);
}

//Continue Game unless win or lose or pause
int continueGame(SDL_Renderer *renderer)
{
    // Check if all rockets have reached the bottom of the screen

    int rocketReachedBottom = 0;
    for (int i = 0; i < MAX_ROCKETS; i++)
    {
        if (rockets[i].y + 45 >= MAX_Y)
        {
            rocketReachedBottom = 1;
            if (rocketReachedBottom)
            {
                quit_flag = 1;
                gameOver(renderer);
                graphicsWriteString(renderer, (MAX_X - SIDE_BAR_WIDTH) / 2 + 30, MAX_Y / 2, "Rockets Reached Bottom.", font);
                return 0;
            }
        }
    }

    if (score == 25)
    {
        quit_flag = 1;
        winGame(renderer);
        score = 0;
        return 0;
    }

    return 1;
}

// Define sleep
void sleep(unsigned int milliseconds)
{
    // Calculate the number of iterations needed for the desired milliseconds
    unsigned int iterations = milliseconds * 10000; // Adjust this value as needed based on your system's clock speed

    // Execute an empty loop for the specified number of iterations
    for (unsigned int i = 0; i < iterations; ++i)
    {
        // Do nothing, just wait
    }
}
//Read keyboard Input
char keyboard_read()
{
    SDL_Event event;
    SDL_PollEvent(&event);
    if (event.type == SDL_KEYDOWN)
    {
        // Get the current key pressed
        char currentKey = event.key.keysym.sym;
        return currentKey;
    }
}

//main function
int main()
{
    SDL_Window *window = NULL;
    SDL_Renderer *renderer = NULL;

    // Initialize SDL
    if (SDL_Init(SDL_INIT_VIDEO) < 0)
    {
        printf("SDL could not initialize! SDL_Error: %s\n", SDL_GetError());
        return 1;
    }

    // Create window
    window = SDL_CreateWindow("Save The World", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, MAX_X, MAX_Y, SDL_WINDOW_SHOWN);
    if (window == NULL)
    {
        printf("Window could not be created! SDL_Error: %s\n", SDL_GetError());
        return 1;
    }

    // Create renderer
    renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_ACCELERATED);
    if (renderer == NULL)
    {
        printf("Renderer could not be created! SDL_Error: %s\n", SDL_GetError());
        return 1;
    }

    // Initialize SDL_ttf
    if (TTF_Init() < 0)
    {
        printf("SDL_ttf could not initialize! SDL_ttf Error: %s\n", TTF_GetError());
        return 1;
    }

    // Load font
    font = TTF_OpenFont("arial.ttf", 18);
    if (font == NULL)
    {
        printf("Failed to load font! SDL_ttf Error: %s\n", TTF_GetError());
        return 1;
    }

    init(renderer);

    // Main event loop

    // //Game loop
    while (1)
    {
        while (quit_flag == 0 && continueGame(renderer))
        {

            current_key = keyboard_read();

            handleUserInput(renderer, current_key, bullets);

            drawSpaceship(renderer, ship_x, ship_y, 4, 4);

            moveBullets(renderer);
            moveRockets(renderer);
            //  Check for collision between bullets and rockets
            collisionBullet(renderer);
            collisionSpaceShip(renderer);

            // Update screen
            SDL_RenderPresent(renderer);
            sleep(800); // Wait for 50 milliseconds using busy wait
        }

        current_key = keyboard_read();
        if (current_key == 'r')
        {
            quit_flag = 0;
            bullet_count = MAX_BULLETS;
            restartGame(renderer); // Restart the game
        }
        if (current_key == 'q')
        {
            SDL_Quit();
        }
        sleep(50);
    }
    return 0;
}
